import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#222222',
    width: '100%',
    height: '100%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#181818',
  },
  headerTextArea: {
    width: 200,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerText: {
    color: '#fff',
    fontSize: 20,
    fontStyle: 'italic',
    fontWeight: 'bold',
  },
  headerButtonLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  buttonArea: {
    width: 60,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5,
    borderBottomColor: '#fff',
    borderBottomWidth: 0.5,
  },
  headerButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  body: {
    flex: 1,
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomableArea: {
    width: '100%',
    height: '100%',
    backgroundColor: '#ffffff',
    borderColor: 'red',
    borderWidth: 10,
    zIndex: 10,
  },
  image: {
    width: 300,
    height: 300,
    minHeight: 80,
    overflow: 'hidden',
    resizeMode: 'contain',
    maxHeight: '100%',
    maxWidth: '100%',
  },
  holeView: {
    position: 'absolute',
    top: -150,
    left: -150,
    // right: -width / 2 + 50,
    // bottom: -width / 2 + 310,
    backgroundColor: 'transparent',
    width: 600,
    height: 600,
    borderWidth: 150,
    borderRadius: 300,
    borderColor: 'black',
    opacity: 0.3,
  },
  zoomableParent: {
    overflow: 'hidden',
    height: 300,
  },
});
